//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kugar.Core.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kugar.Core.Web.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The argument &apos;{0}&apos; cannot be null, empty or contain only white space. 的本地化字符串。
        /// </summary>
        internal static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The associated metadata type for type &apos;{0}&apos; contains the following unknown properties or fields: {1}. Please make sure that the names of these members match the names of the properties on the main type. 的本地化字符串。
        /// </summary>
        internal static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; must be public. 的本地化字符串。
        /// </summary>
        internal static string AttributeStore_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("AttributeStore_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not contain a public method named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AttributeStore_Unknown_Method {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not contain a public property named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AttributeStore_Unknown_Property {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0}.{1} could not be found. 的本地化字符串。
        /// </summary>
        internal static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; and &apos;{1}&apos; do not match. 的本地化字符串。
        /// </summary>
        internal static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find a property named {0}. 的本地化字符串。
        /// </summary>
        internal static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid credit card number. 的本地化字符串。
        /// </summary>
        internal static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must return System.ComponentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnotations.ValidationResult.Success to represent success. 的本地化字符串。
        /// </summary>
        internal static string CustomValidationAttribute_Method_Must_Return_ValidationResult {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute method &apos;{0}&apos; does not exist in type &apos;{1}&apos; or is not public and static. 的本地化字符串。
        /// </summary>
        internal static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute.Method was not specified. 的本地化字符串。
        /// </summary>
        internal static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must match the expected signature: public static ValidationResult {0}(object value, ValidationContext context).  The value can be strongly typed.  The ValidationContext parameter is optional. 的本地化字符串。
        /// </summary>
        internal static string CustomValidationAttribute_Method_Signature {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not convert the value of type &apos;{0}&apos; to &apos;{1}&apos; as expected by method {2}.{3}. 的本地化字符串。
        /// </summary>
        internal static string CustomValidationAttribute_Type_Conversion_Failed {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Conversion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The custom validation type &apos;{0}&apos; must be public. 的本地化字符串。
        /// </summary>
        internal static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not valid. 的本地化字符串。
        /// </summary>
        internal static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute.ValidatorType was not specified. 的本地化字符串。
        /// </summary>
        internal static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The custom DataType string cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} property has not been set.  Use the {1} method to get the value. 的本地化字符串。
        /// </summary>
        internal static string DisplayAttribute_PropertyNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid e-mail address. 的本地化字符串。
        /// </summary>
        internal static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type provided for EnumDataTypeAttribute cannot be null. 的本地化字符串。
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; needs to represent an enumeration type. 的本地化字符串。
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field only accepts files with the following extensions: {1} 的本地化字符串。
        /// </summary>
        internal static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot retrieve property &apos;{0}&apos; because localization failed.  Type &apos;{1}&apos; is not public or does not contain a public static string property with the name &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLength() without parameters to indicate that the string or array can have the maximum allowable length. 的本地化字符串。
        /// </summary>
        internal static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be a string or array type with a maximum length of &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MetadataClassType cannot be null. 的本地化字符串。
        /// </summary>
        internal static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinLengthAttribute must have a Length value that is zero or greater. 的本地化字符串。
        /// </summary>
        internal static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be a string or array type with a minimum length of &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid phone number. 的本地化字符串。
        /// </summary>
        internal static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} must implement {1}. 的本地化字符串。
        /// </summary>
        internal static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum value &apos;{0}&apos; must be greater than or equal to the minimum value &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The minimum and maximum values must be set. 的本地化字符串。
        /// </summary>
        internal static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The OperandType must be set when strings are used for minimum and maximum values. 的本地化字符串。
        /// </summary>
        internal static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be between {1} and {2}. 的本地化字符串。
        /// </summary>
        internal static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must match the regular expression &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pattern must be set to a valid regular expression. 的本地化字符串。
        /// </summary>
        internal static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is required. 的本地化字符串。
        /// </summary>
        internal static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum length must be a nonnegative integer. 的本地化字符串。
        /// </summary>
        internal static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be a string with a maximum length of {1}. 的本地化字符串。
        /// </summary>
        internal static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be a string with a minimum length of {2} and a maximum length of {1}. 的本地化字符串。
        /// </summary>
        internal static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key parameter at position {0} with value &apos;{1}&apos; is not a string. Every key control parameter must be a string. 的本地化字符串。
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNotAString {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key parameter at position {0} is null. Every key control parameter must be a string. 的本地化字符串。
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNull {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key parameter at position {0} with value &apos;{1}&apos; occurs more than once. 的本地化字符串。
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyOccursMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of control parameters must be even. 的本地化字符串。
        /// </summary>
        internal static string UIHintImplementation_NeedEvenNumberOfControlParameters {
            get {
                return ResourceManager.GetString("UIHintImplementation_NeedEvenNumberOfControlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid fully-qualified http, https, or ftp URL. 的本地化字符串。
        /// </summary>
        internal static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Either ErrorMessageString or ErrorMessageResourceName must be set, but not both. 的本地化字符串。
        /// </summary>
        internal static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsValid(object value) has not been implemented by this class.  The preferred entry point is GetValidationResult() and classes should override IsValid(object value, ValidationContext context). 的本地化字符串。
        /// </summary>
        internal static string ValidationAttribute_IsValid_NotImplemented {
            get {
                return ResourceManager.GetString("ValidationAttribute_IsValid_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this attribute. 的本地化字符串。
        /// </summary>
        internal static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property &apos;{0}&apos; on resource type &apos;{1}&apos; is not a string type. 的本地化字符串。
        /// </summary>
        internal static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The resource type &apos;{0}&apos; does not have an accessible static property named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ValidationContext for the type &apos;{0}&apos;, member name &apos;{1}&apos; must provide the MethodInfo. 的本地化字符串。
        /// </summary>
        internal static string ValidationContext_Must_Be_Method {
            get {
                return ResourceManager.GetString("ValidationContext_Must_Be_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A service of type &apos;{0}&apos; already exists in the container. 的本地化字符串。
        /// </summary>
        internal static string ValidationContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The instance provided must match the ObjectInstance on the ValidationContext supplied. 的本地化字符串。
        /// </summary>
        internal static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for property &apos;{0}&apos; must be of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Validator_Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Validator_Property_Value_Wrong_Type", resourceCulture);
            }
        }
    }
}
